name: Develop checks

on:
  pull_request:
    branches:
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t kaleidogram-backend ./backend

  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run ruff check .