name: Lint

on:
  push:
    branches-ignore:
      - develop

jobs:
  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run ruff check .
      - run: poetry run ruff format --check .
